stages:
  - test

format:
  stage: test
  image: devth/helm:latest
  environment: dev
  script:
   
    -  helm repo add bitnami https://charts.bitnami.com/bitnami
    -  helm repo update
    -  helm install my-release bitnami/mongodb -f values.yaml

