
stages:
  #- build
  - test
  #- deployk8s

# build:
#   tags:
#     - docker
#   services:
#     - docker:19.03.12-dind
#   stage: build
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker build -f DockerfileHELLO -t rocket-chat:$CI_PIPELINE_IID .
#     - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
#     - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
#     - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
#     - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
#     - docker rmi rocket-chat:$CI_PIPELINE_IID

 test:
  tags:
    - host
  script:
    - docker -v
  

