# variables:
#     DOCKER_HOST: "tcp://192.168.100.77:2375"
#     #DOCKER_HOST: tcp://docker:2375/
#     DOCKER_DRIVER: overlay2    
#     DOCKER_TLS_CERTDIR: ""

stages:
  - build
  #- test
  #- deployk8s

build:
  tags:
    - host
 # services:
 #   - docker:19.03.12-dind
  stage: build
  script:
    - docker -v
    - docker run hello-world
    - docker ps -a
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -f DockerfileHELLO -t rocket-chat:$CI_PIPELINE_IID .
    # - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
    # - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
    # - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
    # - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
    # - docker rmi rocket-chat:$CI_PIPELINE_IID

# test:
#   tags:
#     - host
#   stage: test
#   script:
#     - docker run hello-world
#     - docker ps -a
    

# example of applying terraform template
# deployterraform:
#   image: hashicorp/terraform/ # or another arbitrary docker image
#   stage: deployterraform
#   script:
#     - hashicorp/terraform:full apply main.tf # or another arbitrary command

# example of deploying to S3
# deploytos3:
#   image: mikesir87/aws-cli # or another arbitrary docker image
#   stage: deploytos3
#   script:
#     - aws s3 sync . s3://example.com/ --delete # or another arbitrary command

# example of deploying to Elastic Beanstalk
# deploytoelasticbeanstalk:
#   image: lciel/eb-cli # or another arbitrary docker image
#   stage: deploytoelasticbeanstalk
#   script:
#     - eb deploy # or another arbitrary command
# stages:
#   - build

# build-job:
#   tags:
#     - docker
#   stage: build
#   script:
    #---work
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker build -t rocket-chat:$CI_PIPELINE_IID .
    # - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
    # - docker tag rocket-chat:$CI_PIPELINE_IID $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
    # - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:$CI_PIPELINE_IID
    # - docker push $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
    # - docker rmi rocket-chat:$CI_PIPELINE_IID

    #--- test deploy job
    # - docker run --name db -d mongo:4.0 --smallfiles --replSet rs0 --oplogSize 128
    # - sleep 10
    # - docker exec -i db mongo --eval "printjson(rs.initiate())"
    # - docker run --name rocketchat -p 80:3000 --link db --env ROOT_URL=http://localhost --env MONGO_OPLOG_URL=mongodb://db:27017/local $CI_REGISTRY/andrew-novogrodski/rocket-chat:latest
    # - sleep 600
