---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretname }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb_root_password }}
  mongodb-password: {{ .Values.mongodb_password }}cm9ja2V0Y2hhdDEyMw==
  mongodb-replica-set-key: {{ .Values.mongodb_replica_set_key }}
  mongo-uri: {{ .Values.mongo_uri }}
  mongo-oplog-uri: {{ .Values.mongo_oplog_uri }}
  mail-url: {{ .Values.mail_url }} 
