---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretname }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-password: cm9vdHJvY2tldGNoYXQ=
  mongodb-password: cm9ja2V0Y2hhdDEyMw==
  mongodb-replica-set-key: cmVwbGljYXJvY2tldGNoYXQ=
  mongo-uri: bW9uZ29kYjovL3JvY2tldGNoYXQ6cm9ja2V0Y2hhdDEyM0Btb25nb2RiLTAubW9uZ29kYi1oZWFkbGVzczoyNzAxNy9yb2NrZXRjaGF0
  mongo-oplog-uri: bW9uZ29kYjovL3Jvb3Q6cm9vdHJvY2tldGNoYXRAbW9uZ29kYi0wLm1vbmdvZGItaGVhZGxlc3M6MjcwMTcvbG9jYWw/cmVwbGljYVNldD1yczAmYXV0aFNvdXJjZT1hZG1pbg==
  mail-url: c210cDovL3NtdHAuZW1haWw=
