---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretname }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb_root_password | b64enc }}
  mongodb-password: {{ .Values.mongodb_password | b64enc }}
  mongodb-replica-set-key: {{ .Values.mongodb_replica_set_key | b64enc }}
  mongo-uri: {{ .Values.mongo_uri | b64enc }}
  mongo-oplog-uri: {{ .Values.mongo_oplog_uri | b64enc }}
  mail-url: {{ .Values.mail_url | b64enc  }} 
