#namespace for deploy
namespace: project

#rocketchat default values 
app:
  name: rocketchat
  containerPort: 3000
  service:
    name: rocket-service
    port: 3000
    targetPort: 3000
  hpa:
    minReplicas: 2
    maxReplicas: 4
    resource:
      cpu: 70
  ingress:
    name: ingress-resource

#mongodb
db:
  name: mongodb
  port: 27017
  replicas: 3
  secretname: mongo
  service:
    name: mongodb-headless
    port: 27017
    targetPort: 27017

#grafana-for-ingress
grafana:
  namespace: monitoring
  name: grafana-prometheus-jk8gk
  port: 80
#scr
mongodb-root-password:123
mongodb-password:5645
mongodb-replica-set-key:53543
mongo-uri:45354
mongo-oplog-uri:5354
mail-url:45345

#docker images:
containers:
  app_image: registry.rocket.chat/rocketchat/rocket.chat:latest
